#!/usr/bin/env python3
"""Apply human-reviewed, high-risk ReceiptSure terminology for priority markets."""

import json
from pathlib import Path


UI = Path("ReceiptArchive/Resources/Localizable.xcstrings")
INFO = Path("ReceiptArchive/Resources/InfoPlist.xcstrings")

LANGUAGES = ("fr", "fr-CA", "de", "ja", "ko", "pt-BR", "pt-PT")
RTL_LANGUAGES = ("ar", "he", "ur")

TERMS = {
    "Settings": ("Réglages", "Réglages", "Einstellungen", "設定", "설정", "Configurações", "Definições"),
    "Merchant rules": ("Règles de commerçants", "Règles de commerçants", "Händlerregeln", "加盟店ルール", "판매처 규칙", "Regras de estabelecimentos", "Regras de comerciantes"),
    "Custom categories": ("Catégories personnalisées", "Catégories personnalisées", "Benutzerdefinierte Kategorien", "カスタムカテゴリ", "사용자 지정 카테고리", "Categorias personalizadas", "Categorias personalizadas"),
    "Capture & accuracy": ("Numérisation et précision", "Numérisation et précision", "Erfassung und Genauigkeit", "スキャンと精度", "스캔 및 정확도", "Captura e precisão", "Captura e precisão"),
    "Encrypted backup & restore": ("Sauvegarde chiffrée et restauration", "Sauvegarde chiffrée et restauration", "Verschlüsseltes Backup und Wiederherstellung", "暗号化バックアップと復元", "암호화 백업 및 복원", "Backup criptografado e restauração", "Cópia de segurança encriptada e restauro"),
    "Private iCloud sync": ("Synchronisation iCloud privée", "Synchronisation iCloud privée", "Privater iCloud-Abgleich", "プライベートiCloud同期", "비공개 iCloud 동기화", "Sincronização privada do iCloud", "Sincronização privada do iCloud"),
    "Share receipt": ("Partager le reçu", "Partager le reçu", "Beleg teilen", "レシートを共有", "영수증 공유", "Compartilhar recibo", "Partilhar recibo"),
    "Delete permanently": ("Supprimer définitivement", "Supprimer définitivement", "Dauerhaft löschen", "完全に削除", "영구 삭제", "Excluir permanentemente", "Eliminar permanentemente"),
    "Delete Permanently": ("Supprimer définitivement", "Supprimer définitivement", "Dauerhaft löschen", "完全に削除", "영구 삭제", "Excluir permanentemente", "Eliminar permanentemente"),
    "Currency": ("Devise", "Devise", "Währung", "通貨", "통화", "Moeda", "Moeda"),
    "Tax label": ("Libellé de taxe", "Libellé de taxe", "Steuerbezeichnung", "税ラベル", "세금 항목", "Descrição do imposto", "Designação do imposto"),
    "Evidence status": ("État des preuves", "État des preuves", "Nachweisstatus", "証明ステータス", "증빙 상태", "Status da comprovação", "Estado do comprovativo"),
    "ReceiptSure Proof Pack": ("Dossier de preuves ReceiptSure", "Dossier de preuves ReceiptSure", "ReceiptSure-Nachweispaket", "ReceiptSure証明パック", "ReceiptSure 증빙 패키지", "Pacote de comprovantes ReceiptSure", "Pacote de comprovativos ReceiptSure"),
    "Unlock Pro for %@": ("Débloquer Pro pour %@", "Débloquer Pro pour %@", "Pro für %@ freischalten", "%@でProを購入", "%@에 Pro 잠금 해제", "Desbloquear o Pro por %@", "Desbloquear o Pro por %@"),
    "No secure backup created": ("Aucune sauvegarde sécurisée créée", "Aucune sauvegarde sécurisée créée", "Noch kein sicheres Backup erstellt", "安全なバックアップはまだありません", "아직 보안 백업이 없습니다", "Nenhum backup seguro foi criado", "Ainda não foi criada uma cópia de segurança segura"),
    "ReceiptSure Pro has been restored.": ("ReceiptSure Pro a été restauré.", "ReceiptSure Pro a été restauré.", "ReceiptSure Pro wurde wiederhergestellt.", "ReceiptSure Proが復元されました。", "ReceiptSure Pro가 복원되었습니다.", "O ReceiptSure Pro foi restaurado.", "O ReceiptSure Pro foi restaurado."),
}

INFO_TERMS = {
    "CFBundleDisplayName": ("ReceiptSure",) * 7,
    "CFBundleName": ("ReceiptSure",) * 7,
    "ReceiptSure Secure Backup": ("Sauvegarde sécurisée ReceiptSure", "Sauvegarde sécurisée ReceiptSure", "Sicheres ReceiptSure-Backup", "ReceiptSure安全バックアップ", "ReceiptSure 보안 백업", "Backup seguro do ReceiptSure", "Cópia de segurança segura do ReceiptSure"),
    "NSCameraUsageDescription": (
        "ReceiptSure utilise l’appareil photo pour numériser, détecter et recadrer les reçus que vous choisissez d’enregistrer.",
        "ReceiptSure utilise l’appareil photo pour numériser, détecter et recadrer les reçus que vous choisissez d’enregistrer.",
        "ReceiptSure verwendet die Kamera, um Belege zu scannen, zu erkennen und zuzuschneiden, die du speichern möchtest.",
        "ReceiptSureは、保存するレシートのスキャン、検出、切り抜きにカメラを使用します。",
        "ReceiptSure는 저장할 영수증을 스캔하고 감지하며 자르기 위해 카메라를 사용합니다.",
        "O ReceiptSure usa a câmera para digitalizar, detectar e recortar os recibos que você escolher salvar.",
        "O ReceiptSure utiliza a câmara para digitalizar, detetar e recortar os recibos que optar por guardar.",
    ),
    "NSFaceIDUsageDescription": (
        "ReceiptSure utilise Face ID pour protéger vos reçus et relevés de dépenses stockés localement.",
        "ReceiptSure utilise Face ID pour protéger vos reçus et relevés de dépenses stockés localement.",
        "ReceiptSure verwendet Face ID, um deine lokal gespeicherten Belege und Ausgabendaten zu schützen.",
        "ReceiptSureは、端末内に保存されたレシートと支出記録を保護するためにFace IDを使用します。",
        "ReceiptSure는 기기에 저장된 영수증과 지출 기록을 보호하기 위해 Face ID를 사용합니다.",
        "O ReceiptSure usa o Face ID para proteger seus recibos e registros de despesas armazenados localmente.",
        "O ReceiptSure utiliza o Face ID para proteger os recibos e registos de despesas guardados localmente.",
    ),
}

RTL_TERMS = {
    "Settings": ("الإعدادات", "הגדרות", "ترتیبات"),
    "Merchant rules": ("قواعد التجار", "כללי בתי עסק", "تجارتی اداروں کے قواعد"),
    "Custom categories": ("فئات مخصصة", "קטגוריות מותאמות אישית", "حسبِ ضرورت زمرے"),
    "Capture & accuracy": ("المسح والدقة", "סריקה ודיוק", "اسکین اور درستگی"),
    "Encrypted backup & restore": ("النسخ الاحتياطي المشفر والاستعادة", "גיבוי מוצפן ושחזור", "خفیہ کردہ بیک اپ اور بحالی"),
    "Private iCloud sync": ("مزامنة iCloud الخاصة", "סנכרון iCloud פרטי", "نجی iCloud مطابقت پذیری"),
    "Share receipt": ("مشاركة الإيصال", "שיתוף קבלה", "رسید شیئر کریں"),
    "Delete permanently": ("حذف نهائيًا", "מחיקה לצמיתות", "مستقل طور پر حذف کریں"),
    "Delete Permanently": ("حذف نهائيًا", "מחיקה לצמיתות", "مستقل طور پر حذف کریں"),
    "Currency": ("العملة", "מטבע", "کرنسی"),
    "Tax label": ("تسمية الضريبة", "תווית מס", "ٹیکس کا لیبل"),
    "Evidence status": ("حالة الإثبات", "מצב הראיות", "ثبوت کی حیثیت"),
    "ReceiptSure Proof Pack": ("حزمة إثبات ReceiptSure", "חבילת הוכחות של ReceiptSure", "ReceiptSure ثبوت پیک"),
    "Unlock Pro for %@": ("فتح Pro مقابل %@", "פתיחת Pro תמורת %@", "%@ کے عوض Pro ان لاک کریں"),
    "No secure backup created": ("لم يتم إنشاء نسخة احتياطية آمنة", "טרם נוצר גיבוי מאובטח", "ابھی تک کوئی محفوظ بیک اپ نہیں بنایا گیا"),
    "ReceiptSure Pro has been restored.": ("تمت استعادة ReceiptSure Pro.", "ReceiptSure Pro שוחזר.", "ReceiptSure Pro بحال ہو گیا ہے۔"),
}

RTL_INFO_TERMS = {
    "CFBundleDisplayName": ("ReceiptSure",) * 3,
    "CFBundleName": ("ReceiptSure",) * 3,
    "ReceiptSure Secure Backup": ("نسخة احتياطية آمنة لـ ReceiptSure", "גיבוי מאובטח של ReceiptSure", "ReceiptSure محفوظ بیک اپ"),
    "NSCameraUsageDescription": (
        "يستخدم ReceiptSure الكاميرا لمسح الإيصالات التي تختار حفظها واكتشافها واقتصاصها.",
        "ReceiptSure משתמש במצלמה כדי לסרוק, לזהות ולחתוך קבלות שתבחרו לשמור.",
        "ReceiptSure آپ کی منتخب کردہ رسیدوں کو اسکین، شناخت اور تراشنے کے لیے کیمرہ استعمال کرتا ہے۔",
    ),
    "NSFaceIDUsageDescription": (
        "يستخدم ReceiptSure ‏Face ID لحماية الإيصالات وسجلات النفقات المخزنة محليًا.",
        "ReceiptSure משתמש ב-Face ID כדי להגן על קבלות ורישומי הוצאות המאוחסנים במכשיר.",
        "ReceiptSure مقامی طور پر محفوظ رسیدوں اور اخراجات کے ریکارڈ کی حفاظت کے لیے Face ID استعمال کرتا ہے۔",
    ),
}

# These strings are the first screen users see in the Settings smoke test.
# They were reviewed together after visual QA exposed mixed-language labels,
# missing spaces, and malformed product copy in several machine drafts.
VISIBLE_LANGUAGES = (
    "ar", "de", "es-ES", "es-MX", "fr", "fr-CA", "he",
    "ja", "ko", "pt-BR", "pt-PT", "ur", "zh-Hans", "zh-Hant",
)

VISIBLE_TERMS = {
    "ReceiptSure Pro": (
        "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro",
        "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro",
        "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro", "ReceiptSure Pro",
        "ReceiptSure Pro", "ReceiptSure Pro",
    ),
    "Unlock Pro — one-time purchase": (
        "فتح Pro — شراء لمرة واحدة", "Pro freischalten — einmaliger Kauf",
        "Desbloquear Pro — compra única", "Desbloquear Pro — compra única",
        "Débloquer Pro — achat unique", "Débloquer Pro — achat unique",
        "פתיחת Pro — רכישה חד-פעמית", "Proを解除 — 1回限りの購入",
        "Pro 잠금 해제 — 일회성 구매", "Desbloquear Pro — compra única",
        "Desbloquear Pro — compra única", "Pro اَن لاک کریں — ایک بار کی خریداری",
        "解锁 Pro — 一次性购买", "解鎖 Pro — 一次購買",
    ),
    "Keep using the free plan, or upgrade once with no subscription.": (
        "استمر في استخدام الخطة المجانية، أو قم بالترقية مرة واحدة من دون اشتراك.",
        "Nutze weiterhin den kostenlosen Plan oder führe ein einmaliges Upgrade ohne Abonnement durch.",
        "Sigue usando el plan gratuito o mejora una sola vez, sin suscripción.",
        "Sigue usando el plan gratuito o mejora una sola vez, sin suscripción.",
        "Continuez avec l’offre gratuite ou passez à Pro une seule fois, sans abonnement.",
        "Continuez avec l’offre gratuite ou passez à Pro une seule fois, sans abonnement.",
        "המשיכו להשתמש בתוכנית החינמית, או שדרגו פעם אחת ללא מנוי.",
        "無料プランを使い続けるか、サブスクリプションなしで一度だけアップグレードできます。",
        "무료 플랜을 계속 사용하거나 구독 없이 한 번만 업그레이드하세요.",
        "Continue usando o plano gratuito ou faça um upgrade único, sem assinatura.",
        "Continue a usar o plano gratuito ou faça uma atualização única, sem subscrição.",
        "مفت پلان استعمال کرتے رہیں، یا سبسکرپشن کے بغیر ایک بار اپ گریڈ کریں۔",
        "继续使用免费计划，或一次性升级，无需订阅。", "繼續使用免費方案，或一次升級，無需訂閱。",
    ),
    "Restore Purchases": (
        "استعادة المشتريات", "Käufe wiederherstellen", "Restaurar compras", "Restaurar compras",
        "Restaurer les achats", "Restaurer les achats", "שחזור רכישות", "購入を復元",
        "구매 복원", "Restaurar compras", "Restaurar compras", "خریداری بحال کریں",
        "恢复购买", "恢復購買",
    ),
    "Your data": (
        "بياناتك", "Ihre Daten", "Tus datos", "Tus datos", "Vos données", "Vos données",
        "הנתונים שלך", "あなたのデータ", "내 데이터", "Seus dados", "Os seus dados",
        "آپ کا ڈیٹا", "你的数据", "你的資料",
    ),
    "Stored on this device": (
        "مخزّن على هذا الجهاز", "Auf diesem Gerät gespeichert", "Guardado en este dispositivo",
        "Guardado en este dispositivo", "Stocké sur cet appareil", "Stocké sur cet appareil",
        "מאוחסן במכשיר זה", "このデバイスに保存", "이 기기에 저장됨",
        "Armazenado neste dispositivo", "Guardado neste dispositivo", "اس ڈیوائس پر محفوظ",
        "存储在此设备上", "儲存在此裝置上",
    ),
    "Receipt images and expense details stay local unless you explicitly enable private iCloud sync.": (
        "تبقى صور الإيصالات وتفاصيل النفقات على الجهاز ما لم تفعّل مزامنة iCloud الخاصة صراحةً.",
        "Belegbilder und Ausgabendetails bleiben auf diesem Gerät, sofern du die private iCloud-Synchronisierung nicht ausdrücklich aktivierst.",
        "Las imágenes de recibos y los detalles de gastos permanecen en el dispositivo, salvo que actives expresamente la sincronización privada con iCloud.",
        "Las imágenes de recibos y los detalles de gastos permanecen en el dispositivo, salvo que actives expresamente la sincronización privada con iCloud.",
        "Les images des reçus et les détails des dépenses restent sur l’appareil, sauf si vous activez explicitement la synchronisation iCloud privée.",
        "Les images des reçus et les détails des dépenses restent sur l’appareil, sauf si vous activez explicitement la synchronisation iCloud privée.",
        "תמונות הקבלות ופרטי ההוצאות נשארים במכשיר, אלא אם מפעילים במפורש סנכרון iCloud פרטי.",
        "レシート画像と支出の詳細は、プライベートiCloud同期を明示的に有効にしない限り、このデバイスに保存されます。",
        "영수증 이미지와 지출 세부 정보는 비공개 iCloud 동기화를 직접 켜지 않는 한 이 기기에만 저장됩니다.",
        "As imagens dos recibos e os detalhes das despesas ficam no dispositivo, a menos que você ative explicitamente a sincronização privada do iCloud.",
        "As imagens dos recibos e os detalhes das despesas ficam no dispositivo, a menos que ative explicitamente a sincronização privada do iCloud.",
        "رسید کی تصاویر اور اخراجات کی تفصیلات اسی ڈیوائس پر رہتی ہیں، جب تک آپ نجی iCloud مطابقت پذیری واضح طور پر فعال نہ کریں۔",
        "收据图像和支出详情会保留在此设备上，除非你明确启用专用 iCloud 同步。",
        "收據影像和支出詳情會保留在此裝置上，除非你明確啟用私人 iCloud 同步。",
    ),
    "Security & continuity": (
        "الأمان والاستمرارية", "Sicherheit und Kontinuität", "Seguridad y continuidad",
        "Seguridad y continuidad", "Sécurité et continuité", "Sécurité et continuité",
        "אבטחה והמשכיות", "セキュリティと継続性", "보안 및 연속성",
        "Segurança e continuidade", "Segurança e continuidade", "سیکیورٹی اور تسلسل",
        "安全与连续性", "安全與連續性",
    ),
    "Require Face ID or passcode": (
        "طلب Face ID أو رمز الدخول", "Face ID oder Code anfordern", "Requerir Face ID o código",
        "Requerir Face ID o código", "Exiger Face ID ou un code", "Exiger Face ID ou un code",
        "דרישת Face ID או קוד גישה", "Face IDまたはパスコードを要求", "Face ID 또는 암호 요구",
        "Exigir Face ID ou código", "Exigir Face ID ou código", "Face ID یا پاس کوڈ درکار",
        "需要 Face ID 或密码", "需要 Face ID 或密碼",
    ),
    "Hide content in app switcher": (
        "إخفاء المحتوى في مبدّل التطبيقات", "Inhalte im App-Umschalter ausblenden",
        "Ocultar contenido en el selector de apps", "Ocultar contenido en el selector de apps",
        "Masquer le contenu dans le sélecteur d’apps", "Masquer le contenu dans le sélecteur d’apps",
        "הסתרת תוכן במחליף היישומים", "Appスイッチャーで内容を隠す", "앱 전환기에서 콘텐츠 가리기",
        "Ocultar conteúdo no seletor de apps", "Ocultar conteúdo no seletor de apps",
        "ایپ سوئچر میں مواد چھپائیں", "在应用切换器中隐藏内容", "在 App 切換器中隱藏內容",
    ),
    "Matters": (
        "المهام", "Vorgänge", "Asuntos", "Asuntos", "Dossiers", "Dossiers", "נושאים",
        "案件", "항목", "Assuntos", "Assuntos", "معاملات", "事项", "事項",
    ),
    "Receipts": (
        "الإيصالات", "Belege", "Recibos", "Recibos", "Reçus", "Reçus", "קבלות",
        "レシート", "영수증", "Recibos", "Recibos", "رسیدیں", "收据", "收據",
    ),
    "Reports": (
        "التقارير", "Berichte", "Informes", "Informes", "Rapports", "Rapports", "דוחות",
        "レポート", "보고서", "Relatórios", "Relatórios", "رپورٹس", "报告", "報告",
    ),
    "Settings": (
        "الإعدادات", "Einstellungen", "Ajustes", "Ajustes", "Réglages", "Réglages", "הגדרות",
        "設定", "설정", "Configurações", "Definições", "ترتیبات", "设置", "設定",
    ),
}

# Spanish capture, review, and filing terminology. These entries are reviewed
# separately from the machine drafts because short English UI labels are highly
# context-sensitive (for example, "crop", "matter", "filing", and "line item").
SPANISH_LANGUAGES = ("es-ES", "es-MX")

SPANISH_WORKFLOW_TERMS = {
    "About": ("Acerca de", "Acerca de"),
    "Add a receipt": ("Añadir un recibo", "Agregar un recibo"),
    "Add a rule to suggest filing details when a merchant matches.": (
        "Añade una regla para sugerir datos de clasificación cuando coincida un comercio.",
        "Agrega una regla para sugerir datos de clasificación cuando coincida un comercio.",
    ),
    "Add explicit conversion": ("Añadir conversión explícita", "Agregar conversión explícita"),
    "Add line item": ("Añadir partida", "Agregar partida"),
    "Add rule": ("Añadir regla", "Agregar regla"),
    "Adjust crop": ("Ajustar recorte", "Ajustar recorte"),
    "All receipts": ("Todos los recibos", "Todos los recibos"),
    "Amount": ("Importe", "Monto"),
    "Apply suggestions": ("Aplicar sugerencias", "Aplicar sugerencias"),
    "Backup complete": ("Copia de seguridad completada", "Respaldo completado"),
    "Backup health": ("Estado de la copia de seguridad", "Estado del respaldo"),
    "Backup password": ("Contraseña de la copia de seguridad", "Contraseña del respaldo"),
    "Backups": ("Copias de seguridad", "Respaldos"),
    "Camera": ("Cámara", "Cámara"),
    "Category name": ("Nombre de la categoría", "Nombre de la categoría"),
    "Check the extracted details": ("Revisar los datos extraídos", "Revisar los datos extraídos"),
    "Check the figures": ("Revisar los importes", "Revisar los montos"),
    "Checked": ("Revisado", "Revisado"),
    "Choose encrypted backup": ("Elegir copia de seguridad cifrada", "Elegir respaldo cifrado"),
    "Client / cost centre": ("Cliente / centro de coste", "Cliente / centro de costos"),
    "Client or cost centre": ("Cliente o centro de coste", "Cliente o centro de costos"),
    "Continue": ("Continuar", "Continuar"),
    "Converted reporting totals": ("Totales convertidos del informe", "Totales convertidos del informe"),
    "Converted total": ("Total convertido", "Total convertido"),
    "Couldn’t crop receipt": ("No se pudo recortar el recibo", "No se pudo recortar el recibo"),
    "Couldn’t re-read receipt": ("No se pudo volver a leer el recibo", "No se pudo volver a leer el recibo"),
    "Couldn’t read receipt": ("No se pudo leer el recibo", "No se pudo leer el recibo"),
    "Couldn’t save category": ("No se pudo guardar la categoría", "No se pudo guardar la categoría"),
    "Couldn’t save matter": ("No se pudo guardar el asunto", "No se pudo guardar el asunto"),
    "Couldn’t save merchant rule": ("No se pudo guardar la regla del comercio", "No se pudo guardar la regla del comercio"),
    "Couldn’t save receipt": ("No se pudo guardar el recibo", "No se pudo guardar el recibo"),
    "Couldn’t share receipt": ("No se pudo compartir el recibo", "No se pudo compartir el recibo"),
    "Create a matter": ("Crear un asunto", "Crear un asunto"),
    "Create encrypted archive": ("Crear archivo cifrado", "Crear archivo cifrado"),
    "Crop page %lld": ("Recortar página %lld", "Recortar página %lld"),
    "Currency": ("Moneda", "Moneda"),
    "Delete Permanently": ("Eliminar definitivamente", "Eliminar definitivamente"),
    "Delete permanently": ("Eliminar definitivamente", "Eliminar definitivamente"),
    "Delete this receipt permanently?": ("¿Eliminar este recibo definitivamente?", "¿Eliminar este recibo definitivamente?"),
    "Drag this handle to the matching receipt corner": (
        "Arrastra este control hasta la esquina correspondiente del recibo",
        "Arrastra este control hasta la esquina correspondiente del recibo",
    ),
    "Edit receipt": ("Editar recibo", "Editar recibo"),
    "Evidence status": ("Estado del justificante", "Estado del comprobante"),
    "Export": ("Exportar", "Exportar"),
    "Export failed": ("No se pudo exportar", "No se pudo exportar"),
    "Field confidence": ("Confianza del campo", "Confianza del campo"),
    "Figures": ("Importes", "Montos"),
    "Filing": ("Clasificación", "Clasificación"),
    "Help & support": ("Ayuda y soporte", "Ayuda y soporte"),
    "Line items": ("Partidas", "Partidas"),
    "Matter": ("Asunto", "Asunto"),
    "Merchant name contains": ("El nombre del comercio contiene", "El nombre del comercio contiene"),
    "Needs review": ("Requiere revisión", "Requiere revisión"),
    "No matters yet": ("Aún no hay asuntos", "Aún no hay asuntos"),
    "No merchant rules": ("No hay reglas de comercios", "No hay reglas de comercios"),
    "No receipts": ("No hay recibos", "No hay recibos"),
    "OCR confidence": ("Confianza del OCR", "Confianza del OCR"),
    "OCR confidence %@": ("Confianza del OCR: %@", "Confianza del OCR: %@"),
    "Scan": ("Escanear", "Escanear"),
    "Scan receipt": ("Escanear recibo", "Escanear recibo"),
    "Sealed": ("Sellado", "Sellado"),
    "Show onboarding again": ("Mostrar de nuevo la introducción", "Mostrar de nuevo la introducción"),
    "Tags, separated by commas": ("Etiquetas, separadas por comas", "Etiquetas, separadas por comas"),
    "Tax label": ("Etiqueta fiscal", "Etiqueta fiscal"),
    "Use Crop": ("Usar recorte", "Usar recorte"),
    "Verified": ("Verificado", "Verificado"),
}

SPANISH_REPORTING_TERMS = {
    "A receipt with the same merchant, date, currency, and total is already saved.": (
        "Ya hay guardado un recibo con el mismo comercio, fecha, moneda y total.",
        "Ya hay guardado un recibo con el mismo comercio, fecha, moneda y total.",
    ),
    "Add another · %lld queued": ("Añadir otro · %lld en cola", "Agregar otro · %lld en cola"),
    "Add end date": ("Añadir fecha de finalización", "Agregar fecha de finalización"),
    "After a crop change, ReceiptSure reads all pages again. Check the refreshed values before saving.": (
        "Tras cambiar el recorte, ReceiptSure vuelve a leer todas las páginas. Revisa los valores actualizados antes de guardar.",
        "Después de cambiar el recorte, ReceiptSure vuelve a leer todas las páginas. Revisa los valores actualizados antes de guardar.",
    ),
    "Apply its category and filing suggestions, then review them before saving.": (
        "Aplica sus sugerencias de categoría y clasificación y revísalas antes de guardar.",
        "Aplica sus sugerencias de categoría y clasificación y revísalas antes de guardar.",
    ),
    "At least 8 characters": ("Al menos 8 caracteres", "Al menos 8 caracteres"),
    "Automation": ("Automatización", "Automatización"),
    "Built-in categories are always available and cannot be removed.": (
        "Las categorías integradas siempre están disponibles y no se pueden eliminar.",
        "Las categorías integradas siempre están disponibles y no se pueden eliminar.",
    ),
    "Camera scanning is unavailable on this device. Photos and Files still work.": (
        "El escaneo con la cámara no está disponible en este dispositivo. Puedes seguir usando Fotos y Archivos.",
        "El escaneo con la cámara no está disponible en este dispositivo. Puedes seguir usando Fotos y Archivos.",
    ),
    "Change record": ("Registro de cambios", "Registro de cambios"),
    "Confidence describes text recognition quality, not whether an expense is valid.": (
        "La confianza indica la calidad del reconocimiento de texto, no si un gasto es válido.",
        "La confianza indica la calidad del reconocimiento de texto, no si un gasto es válido.",
    ),
    "Confirm for new backup": ("Confirmar para la nueva copia", "Confirmar para el nuevo respaldo"),
    "Conversion provenance incomplete": ("Origen de conversión incompleto", "Origen de conversión incompleto"),
    "Create & share backup": ("Crear y compartir copia de seguridad", "Crear y compartir respaldo"),
    "Create a trip, event, or matter, then add its first receipt.": (
        "Crea un viaje, evento o asunto y añade su primer recibo.",
        "Crea un viaje, evento o asunto y agrega su primer recibo.",
    ),
    "Create categories that match your business, project, or reimbursement workflow.": (
        "Crea categorías adaptadas al flujo de trabajo de tu empresa, proyecto o reembolso.",
        "Crea categorías adaptadas al flujo de trabajo de tu negocio, proyecto o reembolso.",
    ),
    "CSV is always free. Your first PDF report is included; unlimited PDF, Excel, Word, JPG, and verifiable Proof Pack exports are available with Pro.": (
        "CSV siempre es gratis. Se incluye tu primer informe PDF; con Pro dispones de exportaciones ilimitadas a PDF, Excel, Word y JPG, además de paquetes de pruebas verificables.",
        "CSV siempre es gratis. Se incluye tu primer informe PDF; con Pro tienes exportaciones ilimitadas a PDF, Excel, Word y JPG, además de paquetes de pruebas verificables.",
    ),
    "Currency conversion": ("Conversión de moneda", "Conversión de moneda"),
    "Dates": ("Fechas", "Fechas"),
    "Detected item total": ("Total de partidas detectadas", "Total de partidas detectadas"),
    "Discount": ("Descuento", "Descuento"),
    "Drag each corner to the edge of the receipt. The result will be straightened before text is read.": (
        "Arrastra cada esquina hasta el borde del recibo. La imagen se enderezará antes de leer el texto.",
        "Arrastra cada esquina hasta el borde del recibo. La imagen se enderezará antes de leer el texto.",
    ),
    "Effective date": ("Fecha efectiva", "Fecha efectiva"),
    "Ends": ("Finaliza", "Finaliza"),
    "Enter manually": ("Introducir manualmente", "Ingresar manualmente"),
    "Expense": ("Gasto", "Gasto"),
    "Expense details": ("Datos del gasto", "Datos del gasto"),
    "Exports leave the app only when you choose a destination in Apple’s share sheet.": (
        "Los datos solo salen de la app cuando eliges un destino en la hoja para compartir de Apple.",
        "Los datos solo salen de la app cuando eliges un destino en la hoja para compartir de Apple.",
    ),
    "Figure exceptions": ("Diferencias en los importes", "Diferencias en los montos"),
    "Figures differ by %@": ("Los importes difieren en %@", "Los montos difieren en %@"),
    "Figures reconcile": ("Los importes cuadran", "Los montos coinciden"),
    "Files": ("Archivos", "Archivos"),
    "Format": ("Formato", "Formato"),
    "Highest risk first": ("Mayor riesgo primero", "Mayor riesgo primero"),
    "I checked the updated details against the image": (
        "He contrastado los datos actualizados con la imagen",
        "Revisé los datos actualizados contra la imagen",
    ),
    "I checked this against the receipt image": (
        "He contrastado estos datos con la imagen del recibo",
        "Revisé estos datos contra la imagen del recibo",
    ),
    "Icon": ("Icono", "Ícono"),
    "Incomplete conversions": ("Conversiones incompletas", "Conversiones incompletas"),
    "Item description": ("Descripción de la partida", "Descripción de la partida"),
    "Keep editing": ("Seguir editando", "Seguir editando"),
    "Keep reviewing": ("Seguir revisando", "Seguir revisando"),
    "Keeps this receipt separate and opens the scanner for the next one.": (
        "Mantiene este recibo separado y abre el escáner para el siguiente.",
        "Mantiene este recibo separado y abre el escáner para el siguiente.",
    ),
    "Last restore": ("Última restauración", "Última restauración"),
    "Lifetime Pro is active": ("Pro de por vida está activo", "Pro de por vida está activo"),
    "Loading receipt image": ("Cargando imagen del recibo", "Cargando imagen del recibo"),
    "Match": ("Coincidencia", "Coincidencia"),
    "Matches “%@”": ("Coincide con «%@»", "Coincide con “%@”"),
    "Matching ignores capitalization. Use a stable part of the merchant name.": (
        "Las coincidencias no distinguen mayúsculas y minúsculas. Usa una parte estable del nombre del comercio.",
        "Las coincidencias no distinguen mayúsculas y minúsculas. Usa una parte estable del nombre del comercio.",
    ),
    "Merchant rule available": ("Regla de comercio disponible", "Regla de comercio disponible"),
    "Merchant, category, or matter": ("Comercio, categoría o asunto", "Comercio, categoría o asunto"),
    "Move %@ to Recently Deleted?": ("¿Mover %@ a Eliminados recientemente?", "¿Mover %@ a Eliminados recientemente?"),
    "Move to Recently Deleted": ("Mover a Eliminados recientemente", "Mover a Eliminados recientemente"),
    "Needs attention": ("Requiere atención", "Requiere atención"),
    "New matter": ("Nuevo asunto", "Nuevo asunto"),
    "New rule": ("Nueva regla", "Nueva regla"),
    "No expenses in this selection": ("No hay gastos en esta selección", "No hay gastos en esta selección"),
    "No line items saved.": ("No hay partidas guardadas.", "No hay partidas guardadas."),
    "No suggestion": ("Sin sugerencia", "Sin sugerencia"),
    "Not now": ("Ahora no", "Ahora no"),
    "Notes": ("Notas", "Notas"),
    "Notes (optional)": ("Notas (opcional)", "Notas (opcional)"),
    "One-time purchase. No subscription.": ("Compra única. Sin suscripción.", "Compra única. Sin suscripción."),
    "Optional notes": ("Notas opcionales", "Notas opcionales"),
    "Payment": ("Pago", "Pago"),
    "PDF with details": ("PDF con datos detallados", "PDF con datos detallados"),
    "Photos": ("Fotos", "Fotos"),
    "Possible duplicate": ("Posible duplicado", "Posible duplicado"),
    "Preparing…": ("Preparando…", "Preparando…"),
    "Privacy": ("Privacidad", "Privacidad"),
    "Privacy Policy": ("Política de privacidad", "Política de privacidad"),
    "Privacy policy": ("Política de privacidad", "Política de privacidad"),
    "PRO": ("PRO", "PRO"),
    "Protection": ("Protección", "Protección"),
    "Purchases": ("Compras", "Compras"),
    "Quantity": ("Cantidad", "Cantidad"),
    "Rate": ("Tipo de cambio", "Tipo de cambio"),
    "Rate date": ("Fecha del tipo de cambio", "Fecha del tipo de cambio"),
    "Rate source": ("Fuente del tipo de cambio", "Fuente del tipo de cambio"),
    "Reading corrected image…": ("Leyendo la imagen corregida…", "Leyendo la imagen corregida…"),
    "Reason for changes (optional)": ("Motivo de los cambios (opcional)", "Motivo de los cambios (opcional)"),
    "Receipt actions": ("Acciones del recibo", "Acciones del recibo"),
    "Receipt images": ("Imágenes de recibos", "Imágenes de recibos"),
    "Receipt status": ("Estado del recibo", "Estado del recibo"),
    "Recently Deleted": ("Eliminados recientemente", "Eliminados recientemente"),
    "Recently Deleted is empty": ("Eliminados recientemente está vacío", "Eliminados recientemente está vacío"),
    "Recognized text": ("Texto reconocido", "Texto reconocido"),
    "Reimbursement": ("Reembolso", "Reembolso"),
    "Report readiness": ("Preparación del informe", "Preparación del informe"),
    "Report scope": ("Contenido del informe", "Contenido del informe"),
    "Reporting currency": ("Moneda del informe", "Moneda del informe"),
    "Reporting currency (e.g. SGD)": ("Moneda del informe (p. ej., SGD)", "Moneda del informe (p. ej., SGD)"),
    "Reporting total": ("Total del informe", "Total del informe"),
    "Reset": ("Restablecer", "Restablecer"),
    "Restore": ("Restaurar", "Restaurar"),
    "Review recommended": ("Se recomienda revisar", "Se recomienda revisar"),
    "Revision history": ("Historial de revisiones", "Historial de revisiones"),
    "Risk %lld": ("Riesgo %lld", "Riesgo %lld"),
    "Rotate": ("Girar", "Girar"),
    "Save anyway": ("Guardar de todos modos", "Guardar de todos modos"),
    "Scan confidence": ("Confianza del escaneo", "Confianza del escaneo"),
    "Seal current evidence": ("Sellar el justificante actual", "Sellar el comprobante actual"),
    "Secure archive error": ("Error del archivo seguro", "Error del archivo seguro"),
    "Sharing": ("Compartiendo", "Compartiendo"),
    "Source": ("Fuente", "Fuente"),
    "Start organizing": ("Empezar a organizar", "Empezar a organizar"),
    "Starts": ("Comienza", "Comienza"),
    "Status": ("Estado", "Estado"),
    "Strong scan": ("Escaneo fiable", "Escaneo confiable"),
    "Subtotal": ("Subtotal", "Subtotal"),
    "Suggested filing": ("Clasificación sugerida", "Clasificación sugerida"),
    "Tags": ("Etiquetas", "Etiquetas"),
    "Text summary": ("Resumen de texto", "Resumen de texto"),
    "Tip": ("Consejo", "Consejo"),
    "Totals": ("Totales", "Totales"),
    "Totals by category": ("Totales por categoría", "Totales por categoría"),
    "Totals by currency": ("Totales por moneda", "Totales por moneda"),
    "Totals by date": ("Totales por fecha", "Totales por fecha"),
    "Trip, event, or matter name": ("Nombre del viaje, evento o asunto", "Nombre del viaje, evento o asunto"),
    "Trips, events & matters": ("Viajes, eventos y asuntos", "Viajes, eventos y asuntos"),
    "Unfiled": ("Sin clasificar", "Sin clasificar"),
    "Unverified receipts will be clearly identified in exported records.": (
        "Los recibos sin verificar se identificarán claramente en los registros exportados.",
        "Los recibos sin verificar se identificarán claramente en los registros exportados.",
    ),
    "Verification": ("Verificación", "Verificación"),
    "Version": ("Versión", "Versión"),
    "You can restore %@ later.": ("Puedes restaurar %@ más adelante.", "Puedes restaurar %@ más adelante."),
}

SPANISH_FINAL_TERMS = {
    "%@ → %@": ("%@ → %@", "%@ → %@"),
    "%@ × %@": ("%@ × %@", "%@ × %@"),
    "%@ confidence %@": ("%@ · confianza %@", "%@ · confianza %@"),
    "%lld receipts": ("%lld recibos", "%lld recibos"),
    "1 receipt": ("1 recibo", "1 recibo"),
    "AES-GCM encrypted snapshot": ("Instantánea cifrada con AES-GCM", "Instantánea cifrada con AES-GCM"),
    "Collection": ("Colección", "Colección"),
    "Couldn’t update categories": ("No se pudieron actualizar las categorías", "No se pudieron actualizar las categorías"),
    "Couldn’t update merchant rules": ("No se pudieron actualizar las reglas de comercios", "No se pudieron actualizar las reglas de comercios"),
    "Couldn’t update receipt": ("No se pudo actualizar el recibo", "No se pudo actualizar el recibo"),
    "Couldn’t update receipts": ("No se pudieron actualizar los recibos", "No se pudieron actualizar los recibos"),
    "Deleting a category removes it from future pickers. Existing receipts keep their category name for accurate historical reports.": (
        "Al eliminar una categoría, dejará de aparecer en los selectores. Los recibos existentes conservarán su nombre para mantener informes históricos precisos.",
        "Al eliminar una categoría, dejará de aparecer en los selectores. Los recibos existentes conservarán su nombre para mantener reportes históricos precisos.",
    ),
    "Edit rule": ("Editar regla", "Editar regla"),
    "Includes receipt images, OCR data, matters, revisions, financial provenance, merchant rules, and custom categories.": (
        "Incluye imágenes de recibos, datos de OCR, asuntos, revisiones, procedencia financiera, reglas de comercios y categorías personalizadas.",
        "Incluye imágenes de recibos, datos de OCR, asuntos, revisiones, procedencia financiera, reglas de comercios y categorías personalizadas.",
    ),
    "Make sure every amount is visible. Adjust the four corners on any page before ReceiptSure reads it.": (
        "Comprueba que todos los importes sean visibles. Ajusta las cuatro esquinas de cada página antes de que ReceiptSure la lea.",
        "Comprueba que todos los montos sean visibles. Ajusta las cuatro esquinas de cada página antes de que ReceiptSure la lea.",
    ),
    "No individual items were detected. You can add them manually if they are needed for allocation or reimbursement.": (
        "No se detectaron partidas individuales. Puedes añadirlas manualmente si las necesitas para imputación o reembolso.",
        "No se detectaron partidas individuales. Puedes agregarlas manualmente si las necesitas para asignación o reembolso.",
    ),
    "No receipts yet": ("Aún no hay recibos", "Aún no hay recibos"),
    "Off by default. If enabled, an AES-GCM encrypted library snapshot and receipt images are stored in your private CloudKit database. The encryption key uses iCloud Keychain so your signed-in devices can decrypt the snapshot.": (
        "Está desactivado de forma predeterminada. Si lo activas, se guardan una instantánea de la biblioteca cifrada con AES-GCM y las imágenes de recibos en tu base de datos privada de CloudKit. La clave de cifrado usa el Llavero de iCloud para que tus dispositivos conectados puedan descifrar la instantánea.",
        "Está desactivado de forma predeterminada. Si lo activas, se guardan una instantánea de la biblioteca cifrada con AES-GCM y las imágenes de recibos en tu base de datos privada de CloudKit. La clave de cifrado usa el Llavero de iCloud para que tus dispositivos conectados puedan descifrar la instantánea.",
    ),
    "OK": ("Aceptar", "Aceptar"),
    "Only receipts with a complete rate, effective date, and source are included.": (
        "Solo se incluyen los recibos que tengan tipo de cambio, fecha efectiva y fuente completos.",
        "Solo se incluyen los recibos que tengan tipo de cambio, fecha efectiva y fuente completos.",
    ),
    "Optional device authentication uses Face ID, Touch ID, or the device passcode. Privacy shielding hides receipt content when the app is not active.": (
        "La autenticación opcional usa Face ID, Touch ID o el código del dispositivo. La protección de privacidad oculta el contenido de los recibos cuando la app no está activa.",
        "La autenticación opcional usa Face ID, Touch ID o el código del dispositivo. La protección de privacidad oculta el contenido de los recibos cuando la app no está activa.",
    ),
    "Original seal": ("Sello original", "Sello original"),
    "Overview": ("Resumen", "Resumen"),
    "Payment is charged to your Apple Account. Purchases can be restored on devices using the same account.": (
        "El pago se carga en tu cuenta de Apple. Puedes restaurar las compras en dispositivos que usen la misma cuenta.",
        "El pago se carga en tu cuenta de Apple. Puedes restaurar las compras en dispositivos que usen la misma cuenta.",
    ),
    "Receipts moved here can be restored or deleted permanently.": (
        "Los recibos que se muevan aquí se pueden restaurar o eliminar definitivamente.",
        "Los recibos que se muevan aquí se pueden restaurar o eliminar definitivamente.",
    ),
    "ReceiptSure": ("ReceiptSure", "ReceiptSure"),
    "ReceiptSure includes no developer account, analytics, advertising, or tracking. The developer does not receive your private iCloud content.": (
        "ReceiptSure no usa cuentas del desarrollador, analítica, publicidad ni seguimiento. El desarrollador no recibe el contenido de tu iCloud privado.",
        "ReceiptSure no usa cuentas del desarrollador, analítica, publicidad ni rastreo. El desarrollador no recibe el contenido de tu iCloud privado.",
    ),
    "Renaming updates existing receipts and merchant rules that use this custom category, preserving consistent reports.": (
        "Al cambiar el nombre, se actualizan los recibos y las reglas de comercios que usan esta categoría personalizada para mantener informes coherentes.",
        "Al cambiar el nombre, se actualizan los recibos y las reglas de comercios que usan esta categoría personalizada para mantener reportes coherentes.",
    ),
    "Restore merges missing records and skips receipt IDs already on this device. It never deletes the current library.": (
        "La restauración incorpora los registros que faltan y omite los identificadores de recibos que ya estén en este dispositivo. Nunca elimina la biblioteca actual.",
        "La restauración incorpora los registros que faltan y omite los identificadores de recibos que ya estén en este dispositivo. Nunca elimina la biblioteca actual.",
    ),
    "Reuse trusted categories and filing details for merchants you visit regularly.": (
        "Reutiliza categorías y datos de clasificación fiables para los comercios que visitas habitualmente.",
        "Reutiliza categorías y datos de clasificación confiables para los comercios que visitas habitualmente.",
    ),
    "Scan a receipt and confirm the extracted figures.": (
        "Escanea un recibo y confirma los importes extraídos.",
        "Escanea un recibo y confirma los montos extraídos.",
    ),
    "Scan the first receipt for this matter.": (
        "Escanea el primer recibo de este asunto.",
        "Escanea el primer recibo de este asunto.",
    ),
    "Scan with automatic cropping, or import an existing image or PDF.": (
        "Escanea con recorte automático o importa una imagen o PDF existente.",
        "Escanea con recorte automático o importa una imagen o PDF existente.",
    ),
    "Secure archives are encrypted locally with AES-GCM and a password-derived key. The password is never stored or uploaded, and restore only adds missing records.": (
        "Los archivos seguros se cifran localmente con AES-GCM y una clave derivada de la contraseña. La contraseña nunca se guarda ni se sube, y la restauración solo añade los registros que faltan.",
        "Los archivos seguros se cifran localmente con AES-GCM y una clave derivada de la contraseña. La contraseña nunca se guarda ni se sube, y la restauración solo agrega los registros que faltan.",
    ),
    "Terms of Use": ("Términos de uso", "Términos de uso"),
    "The password is never stored. Keep it somewhere safe—an archive cannot be restored without it.": (
        "La contraseña nunca se guarda. Consérvala en un lugar seguro: sin ella no se puede restaurar el archivo.",
        "La contraseña nunca se guarda. Consérvala en un lugar seguro: sin ella no se puede restaurar el archivo.",
    ),
    "The receipt image and audit history cannot be recovered after this action.": (
        "La imagen del recibo y el historial de auditoría no se podrán recuperar después de esta acción.",
        "La imagen del recibo y el historial de auditoría no se podrán recuperar después de esta acción.",
    ),
    "The system file picker grants temporary access only to the image or PDF you select. Imported pages are stored inside the app’s private local database.": (
        "El selector de archivos del sistema solo concede acceso temporal a la imagen o PDF que elijas. Las páginas importadas se guardan en la base de datos local privada de la app.",
        "El selector de archivos del sistema solo concede acceso temporal a la imagen o PDF que elijas. Las páginas importadas se guardan en la base de datos local privada de la app.",
    ),
    "The system photo picker can import only the images you select; the app does not request broad photo library access.": (
        "El selector de fotos del sistema solo puede importar las imágenes que elijas; la app no solicita acceso general a la fototeca.",
        "El selector de fotos del sistema solo puede importar las imágenes que elijas; la app no solicita acceso general a la biblioteca de fotos.",
    ),
    "This receipt will be marked Verified.": (
        "Este recibo se marcará como Verificado.",
        "Este recibo se marcará como Verificado.",
    ),
    "Unlimited receipts, matters, reports, and merchant rules are unlocked on this device.": (
        "En este dispositivo están desbloqueados los recibos, asuntos, informes y reglas de comercios ilimitados.",
        "En este dispositivo están desbloqueados los recibos, asuntos, reportes y reglas de comercios ilimitados.",
    ),
    "Used only when you choose to scan a receipt. VisionKit detects the document boundary and crops the image.": (
        "Solo se usa cuando decides escanear un recibo. VisionKit detecta los bordes del documento y recorta la imagen.",
        "Solo se usa cuando decides escanear un recibo. VisionKit detecta los bordes del documento y recorta la imagen.",
    ),
    "You can restore %@ from the Receipts tab.": (
        "Puedes restaurar %@ desde la pestaña Recibos.",
        "Puedes restaurar %@ desde la pestaña Recibos.",
    ),
    "You can save it, but it will remain in Needs Review.": (
        "Puedes guardarlo, pero permanecerá en Requiere revisión.",
        "Puedes guardarlo, pero permanecerá en Requiere revisión.",
    ),
}

SIMPLIFIED_CHINESE_LANGUAGES = ("zh-Hans",)

SIMPLIFIED_CHINESE_WORKFLOW_TERMS = {
    "%@ → %@": ("%@ → %@",),
    "%@ × %@": ("%@ × %@",),
    "%@ confidence %@": ("%@ · 识别置信度 %@",),
    "A receipt with the same merchant, date, currency, and total is already saved.": ("已保存一张商家、日期、币种和总额均相同的收据。",),
    "About": ("关于",),
    "Add a receipt": ("添加收据",),
    "Add a rule to suggest filing details when a merchant matches.": ("添加规则，以便在商家匹配时建议分类归档信息。",),
    "Add another · %lld queued": ("继续添加 · 已有 %lld 张排队",),
    "Add end date": ("添加结束日期",),
    "Add explicit conversion": ("添加明确的货币换算",),
    "Add line item": ("添加明细项",),
    "Add rule": ("添加规则",),
    "Adjust crop": ("调整裁剪",),
    "AES-GCM encrypted snapshot": ("AES-GCM 加密快照",),
    "After a crop change, ReceiptSure reads all pages again. Check the refreshed values before saving.": ("更改裁剪后，ReceiptSure 会重新读取所有页面。保存前请检查更新后的数值。",),
    "All receipts": ("所有收据",),
    "Amount": ("金额",),
    "Apply its category and filing suggestions, then review them before saving.": ("应用其类别和归档建议，并在保存前进行检查。",),
    "Apply suggestions": ("应用建议",),
    "At least 8 characters": ("至少 8 个字符",),
    "Automation": ("自动化",),
    "Backup complete": ("备份完成",),
    "Backup health": ("备份状态",),
    "Backup password": ("备份密码",),
    "Backups": ("备份",),
    "Built-in categories are always available and cannot be removed.": ("内置类别始终可用，无法删除。",),
    "Camera": ("相机",),
    "Camera scanning is unavailable on this device. Photos and Files still work.": ("此设备无法使用相机扫描。你仍可从“照片”或“文件”导入。",),
    "Category name": ("类别名称",),
    "Change record": ("更改记录",),
    "Check the extracted details": ("检查提取的信息",),
    "Check the figures": ("核对金额",),
    "Checked": ("已核对",),
    "Choose encrypted backup": ("选择加密备份",),
    "Client / cost centre": ("客户 / 成本中心",),
    "Client or cost centre": ("客户或成本中心",),
    "Collection": ("收款",),
    "Confidence describes text recognition quality, not whether an expense is valid.": ("置信度表示文字识别质量，并不表示费用是否有效。",),
    "Confirm for new backup": ("确认新备份密码",),
    "Continue": ("继续",),
    "Conversion provenance incomplete": ("换算依据不完整",),
    "Converted reporting totals": ("换算后的报表总额",),
    "Converted total": ("换算后总额",),
    "Couldn’t crop receipt": ("无法裁剪收据",),
    "Couldn’t re-read receipt": ("无法重新读取收据",),
    "Couldn’t read receipt": ("无法读取收据",),
    "Couldn’t save category": ("无法保存类别",),
    "Couldn’t save matter": ("无法保存事项",),
    "Couldn’t save merchant rule": ("无法保存商家规则",),
    "Couldn’t save receipt": ("无法保存收据",),
    "Couldn’t share receipt": ("无法分享收据",),
    "Couldn’t update categories": ("无法更新类别",),
    "Couldn’t update merchant rules": ("无法更新商家规则",),
    "Couldn’t update receipt": ("无法更新收据",),
    "Couldn’t update receipts": ("无法更新收据",),
    "Create & share backup": ("创建并分享备份",),
    "Create a matter": ("创建事项",),
    "Create a trip, event, or matter, then add its first receipt.": ("创建旅行、活动或事项，然后添加第一张收据。",),
    "Create categories that match your business, project, or reimbursement workflow.": ("创建符合业务、项目或报销流程的类别。",),
    "Create encrypted archive": ("创建加密归档",),
    "Crop page %lld": ("裁剪第 %lld 页",),
    "CSV is always free. Your first PDF report is included; unlimited PDF, Excel, Word, JPG, and verifiable Proof Pack exports are available with Pro.": ("CSV 始终免费，并包含首份 PDF 报表。升级 Pro 后可无限导出 PDF、Excel、Word、JPG 和可验证的凭证包。",),
    "Currency": ("币种",),
    "Currency conversion": ("货币换算",),
    "Dates": ("日期",),
    "Delete Permanently": ("永久删除",),
    "Delete permanently": ("永久删除",),
    "Delete this receipt permanently?": ("永久删除此收据？",),
    "Deleting a category removes it from future pickers. Existing receipts keep their category name for accurate historical reports.": ("删除类别后，它将不再出现在选择器中。现有收据仍会保留该类别名称，以确保历史报表准确。",),
    "Detected item total": ("识别出的明细合计",),
    "Discount": ("折扣",),
    "Drag each corner to the edge of the receipt. The result will be straightened before text is read.": ("将四个角分别拖到收据边缘。读取文字前，图像会自动校正。",),
    "Drag this handle to the matching receipt corner": ("将此控制点拖到对应的收据角",),
    "Edit receipt": ("编辑收据",),
    "Edit rule": ("编辑规则",),
    "Effective date": ("生效日期",),
    "Ends": ("结束",),
    "Enter manually": ("手动输入",),
    "Evidence status": ("凭证状态",),
    "Expense": ("费用",),
    "Expense details": ("费用详情",),
    "Export": ("导出",),
    "Export failed": ("导出失败",),
    "Exports leave the app only when you choose a destination in Apple’s share sheet.": ("只有当你在 Apple 分享表单中选择目标位置后，导出内容才会离开本应用。",),
    "Field confidence": ("字段置信度",),
    "Figure exceptions": ("金额差异",),
    "Figures": ("金额",),
    "Figures differ by %@": ("金额相差 %@",),
    "Figures reconcile": ("金额一致",),
    "Files": ("文件",),
    "Filing": ("归档",),
    "Format": ("格式",),
    "Help & support": ("帮助与支持",),
    "Highest risk first": ("风险最高的优先",),
    "I checked the updated details against the image": ("我已对照图像核对更新后的信息",),
    "I checked this against the receipt image": ("我已对照收据图像核对",),
    "Icon": ("图标",),
    "Includes receipt images, OCR data, matters, revisions, financial provenance, merchant rules, and custom categories.": ("包括收据图像、OCR 数据、事项、修订记录、财务来源、商家规则和自定义类别。",),
    "Incomplete conversions": ("换算信息不完整",),
    "Item description": ("明细说明",),
    "Keep editing": ("继续编辑",),
    "Keep reviewing": ("继续检查",),
}


def apply(path: Path, translations, languages=LANGUAGES) -> int:
    payload = json.loads(path.read_text(encoding="utf-8"))
    changed = 0
    for key, values in translations.items():
        entry = payload["strings"][key].setdefault("localizations", {})
        for language, value in zip(languages, values):
            entry[language] = {"stringUnit": {"state": "translated", "value": value}}
            changed += 1
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return changed


changed = apply(UI, TERMS) + apply(INFO, INFO_TERMS)
changed += apply(UI, RTL_TERMS, RTL_LANGUAGES) + apply(INFO, RTL_INFO_TERMS, RTL_LANGUAGES)
changed += apply(UI, VISIBLE_TERMS, VISIBLE_LANGUAGES)
changed += apply(UI, SPANISH_WORKFLOW_TERMS, SPANISH_LANGUAGES)
changed += apply(UI, SPANISH_REPORTING_TERMS, SPANISH_LANGUAGES)
changed += apply(UI, SPANISH_FINAL_TERMS, SPANISH_LANGUAGES)
changed += apply(UI, SIMPLIFIED_CHINESE_WORKFLOW_TERMS, SIMPLIFIED_CHINESE_LANGUAGES)
print(f"Applied {changed} reviewed priority-market entries.")
